"""
Django settings for wayproject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Configuración GDAL para Windows
if os.name == 'nt':  # Windows
    QGIS_PATH = r"C:\Program Files\QGIS 3.44.3"
    os.environ['OSGEO4W_ROOT'] = QGIS_PATH
    os.environ['GDAL_DATA'] = QGIS_PATH + r"\share\gdal"
    os.environ['PROJ_LIB'] = QGIS_PATH + r"\share\proj"
    os.environ['PATH'] = QGIS_PATH + r"\bin;" + os.environ['PATH']
    GDAL_LIBRARY_PATH = QGIS_PATH + r"\bin\gdal311.dll"

from decouple import config

# Configuración para Hugging Face (evitar conexión a internet durante desarrollo)
# Esto previene errores de conexión cuando no hay internet
os.environ.setdefault('HF_HUB_OFFLINE', '0')  # 0 = online, 1 = offline
os.environ.setdefault('TRANSFORMERS_OFFLINE', '0')  # 0 = online, 1 = offline


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-t9(q%-b@kq#6q*@=ci@dc_9(rk)l^-1635!i1b+h&x(w10-n!*'
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    "gastoncelentano.com.ar",
    "www.gastoncelentano.com.ar",
    "200.58.98.187",
    "localhost",
    "127.0.0.1",
]
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')
# Para desarrollo, agregar hosts comunes si está vacío
if not ALLOWED_HOSTS or ALLOWED_HOSTS == ['']:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Para desarrollo
# Agregar testserver para testing
if DEBUG and 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework.authtoken',  # Para autenticación con tokens
    'corsheaders',
    'authentication',  # Nueva app de autenticación
    'moviles',  # Nueva app de móviles
    'gps',
    'agenteIA',  # App de Agente IA Sofia
    'zonas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wayproject.middleware.TimingMiddleware',  # Diagnóstico de performance
]

ROOT_URLCONF = 'wayproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Agregar templates personalizados
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wayproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #'default': {
     #   'ENGINE': 'django.db.backends.sqlite3',
      #  'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}
"""DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT'),
    }
}"""


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST'),
        'PORT': config('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directorio donde collectstatic recopilará todos los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuración de almacenamiento de archivos estáticos con versionado
# Esto agrega hashes a los nombres de archivos para cache busting
# Ejemplo: moviles.js -> moviles.a1b2c3d4.js
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files (archivos subidos por usuarios)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de autenticación
LOGIN_URL = '/login/'  # URL de login personalizada

# Configuración de logging para diagnóstico
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'WARNING',  # Cambiar a 'DEBUG' para ver todas las queries SQL
            'handlers': ['console', 'file'],
        },
        'wayproject.middleware': {
            'level': 'INFO',
            'handlers': ['console', 'file'],
        },
        'gps': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

CSRF_TRUSTED_ORIGINS = [
    # "http://gastoncelentano.com.ar",
    # "http://www.gastoncelentano.com.ar",
    # después agregamos https:
    "https://gastoncelentano.com.ar",
    "https://www.gastoncelentano.com.ar",
]


# Configuración de REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # Requiere auth para escribir
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# Configuración CORS
CORS_ALLOW_ALL_ORIGINS = True  # Para desarrollo. En producción usar CORS_ALLOWED_ORIGINS

# Alternativamente, para más seguridad en desarrollo:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://localhost:5500",
#     "http://127.0.0.1:5500",
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
# ]
CORS_ALLOWED_ORIGINS = [
    # "http://gastoncelentano.com.ar",
    # "http://www.gastoncelentano.com.ar",
    "http://200.58.98.187",
    # más adelante agregamos https cuando esté el certificado:
    "https://gastoncelentano.com.ar",
    "https://www.gastoncelentano.com.ar",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

