# Generated by Django 5.2.7 on 2025-10-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movil',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movil',
            name='gps_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movil',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
