# Generated by Django 4.2.7

from django.db import migrations, models
from django.contrib.gis.db import models as gis_models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_fix_gps_id_null'),
    ]

    operations = [
        # Crear tabla moviles_status
        migrations.CreateModel(
            name='MovilStatus',
            fields=[
                ('movil', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, 
                    primary_key=True, 
                    related_name='status', 
                    serialize=False, 
                    to='gps.movil'
                )),
                ('ultimo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ultimo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ultima_altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ultima_velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ultimo_rumbo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satelites', models.SmallIntegerField(blank=True, null=True)),
                ('hdop', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calidad_senal', models.SmallIntegerField(blank=True, null=True)),
                ('ignicion', models.BooleanField(default=False)),
                ('bateria_pct', models.SmallIntegerField(blank=True, null=True)),
                ('odometro_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_conexion', models.CharField(
                    choices=[
                        ('conectado', 'Conectado'),
                        ('desconectado', 'Desconectado'),
                        ('error', 'Error'),
                    ],
                    default='desconectado',
                    max_length=20
                )),
                ('fecha_gps', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_ultima_posicion', models.BigIntegerField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moviles_status',
                'verbose_name': 'Estado de Móvil',
                'verbose_name_plural': 'Estados de Móviles',
            },
        ),
        
        # Crear tabla moviles_geocode
        migrations.CreateModel(
            name='MovilGeocode',
            fields=[
                ('movil', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, 
                    primary_key=True, 
                    related_name='geocode', 
                    serialize=False, 
                    to='gps.movil'
                )),
                ('direccion_formateada', models.TextField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('piso', models.CharField(blank=True, max_length=20, null=True)),
                ('depto', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pais', models.CharField(default='Argentina', max_length=100)),
                ('fuente_geocodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('confianza_geocodificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('geohash', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_geocodificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'moviles_geocode',
                'verbose_name': 'Geocodificación de Móvil',
                'verbose_name_plural': 'Geocodificaciones de Móviles',
            },
        ),
        
        # Crear tabla posiciones
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rumbo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('satelites', models.SmallIntegerField(blank=True, null=True)),
                ('hdop', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calidad_senal', models.SmallIntegerField(blank=True, null=True)),
                ('ignicion', models.BooleanField(default=False)),
                ('bateria_pct', models.SmallIntegerField(blank=True, null=True)),
                ('odometro_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_gps', models.DateTimeField()),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('calidad_datos', models.CharField(
                    choices=[
                        ('excelente', 'Excelente'),
                        ('buena', 'Buena'),
                        ('regular', 'Regular'),
                        ('mala', 'Mala'),
                    ],
                    default='buena',
                    max_length=20
                )),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('geom', gis_models.PointField(blank=True, null=True, srid=4326)),
                ('movil', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='posiciones', 
                    to='gps.movil'
                )),
            ],
            options={
                'db_table': 'posiciones',
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['-fecha_gps'],
            },
        ),
        
        # Crear tabla cat_moviles
        migrations.CreateModel(
            name='CatMovil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat_moviles',
                'verbose_name': 'Catálogo de Móvil',
                'verbose_name_plural': 'Catálogos de Móviles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        
        # Crear tabla tipos_equipos_gps
        migrations.CreateModel(
            name='TipoEquipoGPS',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('protocolo', models.CharField(
                    choices=[
                        ('TCP', 'TCP'),
                        ('UDP', 'UDP'),
                        ('HTTP', 'HTTP'),
                    ],
                    max_length=10
                )),
                ('puerto_default', models.IntegerField()),
                ('formato_datos', models.JSONField(help_text='Especificación del formato de datos')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_equipos_gps',
                'verbose_name': 'Tipo de Equipo GPS',
                'verbose_name_plural': 'Tipos de Equipos GPS',
            },
        ),
        
        # Crear tabla configuraciones_receptores
        migrations.CreateModel(
            name='ConfiguracionReceptor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puerto', models.IntegerField(unique=True)),
                ('protocolo', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('max_conexiones', models.IntegerField(default=100)),
                ('max_equipos', models.IntegerField(default=1000)),
                ('timeout', models.IntegerField(default=30)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('prioridad', models.IntegerField(default=1)),
                ('configuracion_avanzada', models.JSONField(blank=True, null=True)),
                ('tipo_equipo', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='gps.tipoequipogps'
                )),
            ],
            options={
                'db_table': 'configuraciones_receptores',
                'verbose_name': 'Configuración de Receptor',
                'verbose_name_plural': 'Configuraciones de Receptores',
            },
        ),
        
        # Crear tabla estadisticas_recepcion
        migrations.CreateModel(
            name='EstadisticasRecepcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('equipos_conectados', models.IntegerField(default=0)),
                ('datos_recibidos', models.IntegerField(default=0)),
                ('datos_procesados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('latencia_promedio', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('receptor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='gps.configuracionreceptor'
                )),
            ],
            options={
                'db_table': 'estadisticas_recepcion',
                'verbose_name': 'Estadística de Recepción',
                'verbose_name_plural': 'Estadísticas de Recepción',
            },
        ),
        
        # Crear índices para optimización
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_moviles_status_estado_conexion ON moviles_status(estado_conexion);",
            reverse_sql="DROP INDEX IF EXISTS idx_moviles_status_estado_conexion;"
        ),
        
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_moviles_status_fecha_gps ON moviles_status(fecha_gps);",
            reverse_sql="DROP INDEX IF EXISTS idx_moviles_status_fecha_gps;"
        ),
        
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_posiciones_movil_fecha ON posiciones(movil_id, fecha_gps);",
            reverse_sql="DROP INDEX IF EXISTS idx_posiciones_movil_fecha;"
        ),
        
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_posiciones_fecha_gps ON posiciones(fecha_gps);",
            reverse_sql="DROP INDEX IF EXISTS idx_posiciones_fecha_gps;"
        ),
        
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_posiciones_calidad_datos ON posiciones(calidad_datos);",
            reverse_sql="DROP INDEX IF EXISTS idx_posiciones_calidad_datos;"
        ),
        
        # Agregar constraint único para estadisticas_recepcion
        migrations.RunSQL(
            "ALTER TABLE estadisticas_recepcion ADD CONSTRAINT unique_estadisticas_receptor_fecha UNIQUE (receptor_id, fecha);",
            reverse_sql="ALTER TABLE estadisticas_recepcion DROP CONSTRAINT IF EXISTS unique_estadisticas_receptor_fecha;"
        ),
    ]
