# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0007_create_new_tables_simple'),
    ]

    operations = [
        # Eliminar campos obsoletos del modelo Movil
        # Estos campos ahora están en moviles_status, moviles_geocode y posiciones
        
        # Campos de posición GPS (ahora en moviles_status)
        migrations.RemoveField(
            model_name='movil',
            name='ultimo_lat',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ultimo_lon',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ultimo_rumbo',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ultima_velocidad_kmh',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ultima_altitud_m',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ult_satelites',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ultimo_hdop',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='fecha_gps',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='fecha_recepcion',
        ),
        
        # Campos de telemetría (ahora en moviles_status)
        migrations.RemoveField(
            model_name='movil',
            name='ignicion',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='bateria_pct',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='odometro_km',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='km_calculado',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='km_ultimo_calculo_at',
        ),
        
        # Campos de geocodificación (ahora en moviles_geocode)
        migrations.RemoveField(
            model_name='movil',
            name='dir_formateada',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_calle',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_numero',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_piso',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_depto',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_barrio',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_localidad',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_municipio',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_provincia',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_cp',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='dir_pais',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='geo_fuente',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='geo_confianza',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='geo_actualizado_at',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='geo_geohash',
        ),
        
        # Campos de payload crudo (ahora en moviles_status)
        migrations.RemoveField(
            model_name='movil',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='raw_json',
        ),
        
        # Campos de geometría (ahora en posiciones)
        migrations.RemoveField(
            model_name='movil',
            name='geom',
        ),
        
        # Campos de iconos (ahora en cat_moviles)
        migrations.RemoveField(
            model_name='movil',
            name='icono_tipo',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='icono_color_hex',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='icono_url',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='icono_rotacion_modo',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='icono_rotacion_grados',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='icono_escala',
        ),
    ]
