# Generated by Django 5.2.7 on 2025-10-20 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0008_clean_movil_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=15, unique=True, verbose_name='IMEI')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Serie')),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Equipo GPS',
                'verbose_name_plural': 'Equipos GPS',
                'db_table': 'equipos_gps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovilFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen del móvil', upload_to='moviles/fotos/%Y/%m/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('documentos', 'Documentos'), ('danos', 'Daños'), ('mantenimiento', 'Mantenimiento'), ('accesorios', 'Accesorios'), ('general', 'General')], default='general', max_length=50)),
                ('tamaño_archivo', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('dimensiones', models.CharField(blank=True, help_text='Ancho x Alto en píxeles', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('es_principal', models.BooleanField(default=False, help_text='Foto principal del móvil')),
                ('visible', models.BooleanField(default=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foto de Móvil',
                'verbose_name_plural': 'Fotos de Móviles',
                'db_table': 'moviles_fotos',
                'ordering': ['orden', '-fecha_captura'],
            },
        ),
        migrations.CreateModel(
            name='MovilNota',
            fields=[
                ('movil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nota_general', serialize=False, to='gps.movil')),
                ('contenido', models.TextField(blank=True, help_text='Notas generales sobre el móvil')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota de Móvil',
                'verbose_name_plural': 'Notas de Móviles',
                'db_table': 'moviles_notas',
            },
        ),
        migrations.CreateModel(
            name='MovilObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('general', 'General'), ('mantenimiento', 'Mantenimiento'), ('incidente', 'Incidente'), ('documentacion', 'Documentación'), ('reparacion', 'Reparación'), ('inspeccion', 'Inspección')], default='general', max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En Proceso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Observación de Móvil',
                'verbose_name_plural': 'Observaciones de Móviles',
                'db_table': 'moviles_observaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='catmovil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='configuracionreceptor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadisticasrecepcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadisticasrecepcion',
            name='latencia_promedio',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoequipogps',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='estadisticasrecepcion',
            unique_together={('receptor', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='movilgeocode',
            index=models.Index(fields=['provincia', 'localidad'], name='moviles_geo_provinc_55b9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='movilgeocode',
            index=models.Index(fields=['fecha_geocodificacion'], name='moviles_geo_fecha_g_891afd_idx'),
        ),
        migrations.AddIndex(
            model_name='movilstatus',
            index=models.Index(fields=['estado_conexion'], name='moviles_sta_estado__d05483_idx'),
        ),
        migrations.AddIndex(
            model_name='movilstatus',
            index=models.Index(fields=['fecha_gps'], name='moviles_sta_fecha_g_f9a73a_idx'),
        ),
        migrations.AddIndex(
            model_name='movilstatus',
            index=models.Index(fields=['ultima_actualizacion'], name='moviles_sta_ultima__c7edbd_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['movil', 'fecha_gps'], name='posiciones_movil_i_4a3d81_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['fecha_gps'], name='posiciones_fecha_g_d5714c_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['calidad_datos'], name='posiciones_calidad_403fb6_idx'),
        ),
        migrations.AddField(
            model_name='movilfoto',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='gps.movil'),
        ),
        migrations.AddField(
            model_name='movilfoto',
            name='usuario_captura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_capturadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movilnota',
            name='usuario_actualizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movilobservacion',
            name='movil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='gps.movil'),
        ),
        migrations.AddField(
            model_name='movilobservacion',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movilobservacion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movilfoto',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='gps.movilobservacion'),
        ),
        migrations.AddIndex(
            model_name='movilobservacion',
            index=models.Index(fields=['movil', 'fecha_creacion'], name='moviles_obs_movil_i_084e98_idx'),
        ),
        migrations.AddIndex(
            model_name='movilobservacion',
            index=models.Index(fields=['categoria'], name='moviles_obs_categor_3ae7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='movilobservacion',
            index=models.Index(fields=['estado'], name='moviles_obs_estado_980fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='movilobservacion',
            index=models.Index(fields=['prioridad'], name='moviles_obs_priorid_59475b_idx'),
        ),
        migrations.AddIndex(
            model_name='movilfoto',
            index=models.Index(fields=['movil', 'orden'], name='moviles_fot_movil_i_980046_idx'),
        ),
        migrations.AddIndex(
            model_name='movilfoto',
            index=models.Index(fields=['categoria'], name='moviles_fot_categor_237cee_idx'),
        ),
        migrations.AddIndex(
            model_name='movilfoto',
            index=models.Index(fields=['es_principal'], name='moviles_fot_es_prin_34e4a4_idx'),
        ),
        migrations.AddIndex(
            model_name='movilfoto',
            index=models.Index(fields=['fecha_captura'], name='moviles_fot_fecha_c_3d30e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='movilfoto',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('movil',), name='unique_foto_principal_por_movil'),
        ),
    ]
