# Generated by Django 5.2.7 on 2025-10-23 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0009_add_observaciones_fotos_notas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'managed': True, 'verbose_name': 'Equipo GPS', 'verbose_name_plural': 'Equipos GPS'},
        ),
    ]
